name: "setup yarn"
description: "setup caches and run install"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.node-version'
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    - name: yarn install
      shell: bash
      run: yarn install --frozen-lockfile
