name: "setup yarn"
description: "setup caches and run install"
runs:
  using: "composite"
  steps:
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "yarn-cache-dir-path=$(yarn config get cacheFolder)" >> $GITHUB_ENV

    - name: restore yarn cache
      uses: actions/cache@v3
      with:
        path: ${{ env.yarn-cache-dir-path }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('.node-version') }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: restore node_modules
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-${{ hashFiles('.node-version') }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: yarn install
      shell: bash
      run: yarn install
