name: Check PR
on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  check:
    name: check lint and test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: run danger
        shell: bash
        run: |
          yarn run danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
